### ISSUE TITLE
Collection Maintainership - Ansible Certification Program

### ISSUE THREAD

**Issue by alisonlhart** [newrelic/newrelic-agents-ansible-collection#2]
Hello,

I'm reaching out as part of the Ansible Partner Engineering team to check on collection maintainership. @njvrzm Are you still maintaining this collection or is there another contact we can reach out to that you know of? 

This collection currently has only been tested on ansible 2.9, and to maintain certification on Ansible Automation Hub we will need the collection to be tested on at least ansible-core 2.11 or higher versions by the 2.9 EOL date - September 2023. 

Please let me know if there is anything I can assist with from the Partner Engineering side.

Thanks.

**Comment by njvrzm** [comment]
Hi @alisonlhart - thanks for reaching out. I left New Relic a couple of years ago and I'm afraid I don't know who might be able to take this repo over. Based on contributors to the more actively-maintained [Infrastructure agent role](https://github.com/newrelic/infrastructure-agent-ansible) you might try @rogercoll or @kidk.

**Comment by alisonlhart** [comment]
@njvrzm Thanks for the info. That's what we were thinking, but wanted to confirm with you. I appreciate it!
